syntax = "proto3";

package parking.v1;

option go_package = "github.com/nalrematvonesah/parking.proto/gen/parking/v1;parkingv1";

service ParkingService {
  rpc AssignSlot(AssignSlotRequest) returns (AssignSlotResponse);
  rpc ReleaseSlot(ReleaseSlotRequest) returns (Empty);
  rpc GetAvailableSlots(Empty) returns (AvailableSlotsResponse);
  rpc GetSlot(GetSlotRequest) returns (SlotResponse);         
  rpc ListAllSlots(Empty) returns (ListSlotsResponse);       
  rpc AddSlots(AddSlotsRequest) returns (Empty);              
}

message AssignSlotRequest {
  string request_id = 1;
}

message AssignSlotResponse {
  int64 slot_id = 1;
}

message ReleaseSlotRequest {
  int64 slot_id = 1;
}

message AvailableSlotsResponse {
  int32 count = 1;
}

message GetSlotRequest {
  int64 slot_id = 1;
}

message SlotResponse {
  int64 slot_id = 1;
  bool is_occupied = 2;
}

message ListSlotsResponse {
  repeated SlotResponse slots = 1;
}

message AddSlotsRequest {
  int32 count = 1;
}

message Empty {}